layout_spectrum: 0.6698605
typography_spectrum: 0.01442534
color:
  saturation: 0.1380662
  lightness: 0.8801165
  brandStrength: 0.3604582
  rhythmicContrast: 0.03307706
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: yicreative photos
